{{ config (
  materialized= 'view',
  schema= 'SQUARE',
  tags= ["staging", "daily"]
)
}}

WITH source AS (
  SELECT 
  * 
  FROM  	
    {{source('OLD_SQUARE','CUSTOMER')}}
),
rename AS 
(   
SELECT 
    --MD5 KEYS
     MD5( TRIM(COALESCE(ID, '00000000000000000000000000000000')) ) AS K_POS_CUSTOMER_CUSTOMER_DLHK
    --BUSINESS KEYS
    ,ID AS A_POS_CUSTOMER_CUSTOMER_BK
    --ATTRIBUTES
    ,GIVEN_NAME AS A_POS_CUSTOMER_GIVEN_NAME
    ,FAMILY_NAME AS A_POS_CUSTOMER_FAMILY_NAME
    ,{{full_name('GIVEN_NAME', 'FAMILY_NAME')}} AS A_POS_CUSTOMER_FULL_NAME
    ,EMAIL_ADDRESS AS A_POS_CUSTOMER_EMAIL
    ,ADDRESS_ADDRESS_LINE_1 AS A_POS_CUSTOMER_ADDR_LINE_1
    ,ADDRESS_ADDRESS_LINE_2 AS A_POS_CUSTOMER_ADDR_LINE_2
    ,ADDRESS_ADDRESS_LINE_3 AS A_POS_CUSTOMER_ADDR_LINE_3
    ,ADDRESS_LOCALITY AS A_POS_CUSTOMER_ADDR_LOCAL
    ,ADDRESS_SUBLOCALITY AS A_POS_CUSTOMER_ADDR_SUBLOCAL
    ,ADDRESS_POSTAL_CODE AS A_POS_CUSTOMER_ADDR_POSTAL_CODE
    ,ADDRESS_COUNTRY AS A_POS_CUSTOMER_ADDR_COUNTRY
    ,PHONE_NUMBER AS A_POS_CUSTOMER_PHONE_NUM
    ,BIRTHDAY AS A_POS_CUSTOMER_BIRTHDAY
    ,REFERENCE_ID AS A_POS_CUSTOMER_REFERENCE_ID  
    , CASE WHEN EMAIL_ADDRESS IS NOT NULL THEN 'POSLOYAL' ELSE 'ANONYMOUS' END
    AS A_POS_GB_CONSUMER_TYPE
  FROM
      source    
)


SELECT * FROM rename