{{ config (
  materialized= 'view',
  schema= 'SQUARE',
  tags= ["staging", "daily"]
)
}}

WITH source AS (
  SELECT 
  * 
  FROM  	
    {{source('OLD_SQUARE','CUSTOMER')}}
),
rename AS 
(  
    SELECT
        ID AS CUSTOMER_ID,
        GIVEN_NAME AS GIVEN_NAME,
        FAMILY_NAME AS FAMILY_NAME,
        {{full_name('GIVEN_NAME', 'FAMILY_NAME')}} AS FULL_NAME,
        NICKNAME AS NICKNAME,
        EMAIL_ADDRESS AS EMAIL_ADDRESS,
        PHONE_NUMBER AS PHONE_NUMBER,
        COMPANY_NAME AS COMPANY_NAME,
        BIRTHDAY AS BIRTHDAY,
        ADDRESS_ADDRESS_LINE_1 AS ADDRESS_ADDRESS_LINE_1,
        ADDRESS_ADDRESS_LINE_2 AS ADDRESS_ADDRESS_LINE_2,
        ADDRESS_ADDRESS_LINE_3 AS ADDRESS_ADDRESS_LINE_3,
        ADDRESS_LOCALITY AS ADDRESS_LOCALITY,
        ADDRESS_SUBLOCALITY AS ADDRESS_SUBLOCALITY,
        ADDRESS_SUBLOCALITY_2 AS ADDRESS_SUBLOCALITY_2,
        ADDRESS_SUBLOCALITY_3 AS ADDRESS_SUBLOCALITY_3,
        ADDRESS_ADMINISTRATIVE_DISTRICT_LEVEL_1 AS ADDRESS_ADMINISTRATIVE_DISTRICT_LEVEL_1,
        ADDRESS_ADMINISTRATIVE_DISTRICT_LEVEL_2 AS ADDRESS_ADMINISTRATIVE_DISTRICT_LEVEL_2,
        ADDRESS_ADMINISTRATIVE_DISTRICT_LEVEL_3 AS ADDRESS_ADMINISTRATIVE_DISTRICT_LEVEL_3,
        ADDRESS_POSTAL_CODE AS ADDRESS_POSTAL_CODE,
        ADDRESS_COUNTRY AS ADDRESS_COUNTRY,
        ADDRESS_FIRST_NAME AS ADDRESS_FIRST_NAME,
        ADDRESS_LAST_NAME AS ADDRESS_LAST_NAME,
        ADDRESS_ORGANIZATION AS ADDRESS_ORGANIZATION,
        CREATION_SOURCE AS CREATION_SOURCE,
        PREFERENCES_EMAIL_UNSUBSCRIBED AS PREFERENCES_EMAIL_UNSUBSCRIBED,
        --SEGMENT_IDS AS SEGMENT_IDS,
        REFERENCE_ID AS REFERENCE_ID,
        NOTE AS NOTE,
        CREATED_AT AS CREATED_AT,
        UPDATED_AT AS UPDATED_AT
    FROM
    source
)


SELECT * FROM rename