{{ config (
  materialized= 'view',
  schema= 'SQUARE',
  tags= ["staging", "daily"]
)
}}

WITH source AS (
  SELECT * FROM  {{source('OLD_SQUARE','ORDER_LINE_ITEM_MODIFIER')}}
),

rename AS 
(
 SELECT
        --MD5 KEYS
        MD5( UID ) AS K_POS_ORDER_ITEM_MODIFIER_DLHK 
        ,MD5( TRIM(COALESCE(ORDER_ID, '00000000000000000000000000000000'))  ) AS K_POS_ORDER_DLHK
        ,MD5( TRIM(COALESCE(ORDER_LINE_ITEM_ID, '00000000000000000000000000000000'))  ) AS K_POS_ORDER_LINE_ITEM_DLHK
        ,MD5( TRIM(COALESCE(CATALOG_OBJECT_ID, '00000000000000000000000000000000')) ) AS K_POS_CATALOG_OBJECT_DLHK         
        --BUSINESS KEYS
        ,UID AS K_POS_ORDER_ITEM_MODIFIER_BK        
        ,ORDER_ID AS K_POS_ORDER_BK
        ,ORDER_LINE_ITEM_ID AS K_POS_ORDER_LINE_ITEM_BK
        ,CATALOG_OBJECT_ID AS K_POS_CATALOG_OBJECT_BK
        --METRICS
        ,BASE_PRICE_AMOUNT AS M_BASE_PRICE_AMOUNT
        ,TOTAL_PRICE_AMOUNT AS M_TOTAL_PRICE_AMOUNT        
        --DESCRIPTION AND DATE FIELDS
        ,BASE_PRICE_CURRENCY AS A_BASE_PRICE_CURRENCY
        ,TOTAL_PRICE_CURRENCY AS A_TOTAL_PRICE_CURRENCY        
        --METADATA
        , CURRENT_TIMESTAMP AS MD_LOAD_DTS
        , '{{invocation_id}}' AS MD_INTGR_ID
FROM source 
)

SELECT * FROM rename