{{ config (
  materialized= 'view',
  schema= 'SQUARE',
  tags= ["staging", "daily"]
)
}}

WITH source AS (
  SELECT * FROM  {{source('OLD_SQUARE','ORDER_LINE_ITEM')}}
),

rename AS 
(
  SELECT 
--MD5 KEYS 
  MD5 (UID) AS K_POS_ORDER_LINE_DLHK
  ,MD5 (TRIM(ORDER_ID)) AS K_POS_ORDER_DLHK
  ,MD5( TRIM(COALESCE(CATALOG_OBJECT_ID, '00000000000000000000000000000000'))  ) AS K_POS_CATALOG_OBJECT_DLHK
  ,MD5( TRIM(COALESCE(TOTAL_CURRENCY, '00000000000000000000000000000000')) ) AS K_CURRENCY_DLHK
--BUSINESS KEYS
  ,UID AS K_POS_ORDER_LINE_BK
  ,ORDER_ID AS K_POS_ORDER_BK  
  ,CATALOG_OBJECT_ID AS K_POS_CATALOG_OBJECT_BK
--OTHER FIELDS
  ,NAME AS A_POS_ORDER_LINE_NAME
  ,QUANTITY AS M_POS_ORDER_LINE_QUANTITY
  ,NOTE AS A_POS_ORDER_LINE_NOTE  
  ,VARIATION_NAME AS A_POS_ORDER_LINE_VARIATION_NAME
  ,ROUND(NVL(BASE_PRICE_AMOUNT, 000)/100, 2)::decimal(15,2) AS M_ORDER_LINE_BASE_PRICE_AMT
  ,ROUND(NVL(GROSS_SALES_AMOUNT, 000)/100, 2)::decimal(15,2) AS M_ORDER_LINE_GROSS_SALES_AMT
  ,ROUND(NVL(TOTAL_TAX_AMOUNT, 000)/100, 2)::decimal(15,2) AS M_ORDER_LINE_TOTAL_TAX_AMT
  ,ROUND(NVL(TOTAL_DISCOUNT_AMOUNT, 000)/100, 2)::decimal(15,2) AS M_ORDER_LINE_TOTAL_DISCOUNT_AMT
  ,ROUND(NVL(TOTAL_AMOUNT, 000)/100, 2)::decimal(15,2) AS M_ORDER_LINE_TOTAL_AMT
  ,ROUND(NVL(GROSS_SALES_AMOUNT, 000)/100, 2) - ROUND(NVL(TOTAL_DISCOUNT_AMOUNT, 000)/100, 2) AS M_POS_ITEM_NET_AMT
FROM source
)

SELECT * FROM rename