{{ config (
  materialized= 'view',
  schema= 'SQUARE',
  tags= ["staging", "daily"]
)
}}

WITH source AS (
  SELECT * FROM  {{source('OLD_SQUARE','ORDER')}} AS A
),
rename AS 
(
SELECT 
--PKs
  ID AS ORDER_ID,
--FOREIGN KEYS
  LOCATION_ID,
  CUSTOMER_ID,
  REFERENCE_ID,
--DATE FIELDS
  CREATED_AT,
  UPDATED_AT,
  CLOSED_AT,
--OTHER FIELDS  
  ORDER_SOURCE_NAME,
  TOTAL_TAX_AMOUNT,
  TOTAL_TAX_CURRENCY,
  TOTAL_DISCOUNT_AMOUNT,
  TOTAL_DISCOUNT_CURRENCY,
  TOTAL_TIP_AMOUNT,
  TOTAL_TIP_CURRENCY,
  TOTAL_MONEY_AMOUNT,
  TOTAL_MONEY_CURRENCY,
  TOTAL_SERVICE_CHARGE_AMOUNT,
  TOTAL_SERVICE_CHARGE_CURRENCY,
  RETURN_AMOUNT_TOTAL_MONEY_AMOUNT,
  RETURN_AMOUNT_TOTAL_MONEY_CURRENCY,
  RETURN_AMOUNT_TAX_MONEY_AMOUNT,
  RETURN_AMOUNT_TAX_MONEY_CURRENCY,
  RETURN_AMOUNT_DISCOUNT_MONEY_AMOUNT,
  RETURN_AMOUNT_DISCOUNT_MONEY_CURRENCY,
  RETURN_AMOUNT_TIP_MONEY_AMOUNT,
  RETURN_AMOUNT_TIP_MONEY_CURRENCY,
  RETURN_AMOUNT_SERVICE_CHARGE_MONEY_AMOUNT,
  RETURN_AMOUNT_SERVICE_CHARGE_MONEY_CURRENCY,
  NET_AMOUNT_TOTAL_MONEY_AMOUNT,
  NET_AMOUNT_TOTAL_MONEY_CURRENCY,
  NET_AMOUNT_TAX_MONEY_AMOUNT,
  NET_AMOUNT_TAX_MONEY_CURRENCY,
  NET_AMOUNT_DISCOUNT_MONEY_AMOUNT,
  NET_AMOUNT_DISCOUNT_MONEY_CURRENCY,
  NET_AMOUNT_TIP_MONEY_AMOUNT,
  NET_AMOUNT_TIP_MONEY_CURRENCY,
  NET_AMOUNT_SERVICE_CHARGE_MONEY_AMOUNT,
  NET_AMOUNT_SERVICE_CHARGE_MONEY_CURRENCY,
  ROUNDING_ADJUSTMENT_UID,
  ROUNDING_ADJUSTMENT_NAME,
  ROUNDING_ADJUSTMENT_AMOUNT_MONEY_AMOUNT,
  ROUNDING_ADJUSTMENT_AMOUNT_MONEY_CURRENCY,
  STATE AS  ORDER_STATE,
  VERSION AS ORDER_VERSION
FROM source
)

SELECT * FROM rename