{{ config (
  materialized= 'view',
  schema= 'SQUARE',
  tags= ["staging", "daily"]
)
}}

WITH source AS (
  SELECT * FROM  	{{source('OLD_SQUARE','ORDER_DISCOUNT')}}
),

renamed_casted AS 
(
SELECT 
UID AS ORDERDISCOUNT_ID,
ORDER_ID AS ORDERDISCOUNT_ORDER_ID,
CATALOG_OBJECT_ID AS ORDERDISCOUNT_CATALOG_OBJECT_ID,
NAME AS ORDERDISCOUNT_NAME,
PERCENTAGE AS ORDERDISCOUNT_PERCENTAGE,
TYPE AS ORDERDISCOUNT_TYPE,
SCOPE AS ORDERDISCOUNT_SCOPE,
PRICING_RULE_ID AS ORDERDISCOUNT_PRICING_RULE_ID,
REWARD_IDS AS ORDERDISCOUNT_REWARD_IDS,
APPLIED_MONEY_AMOUNT AS ORDERDISCOUNT_APPLIED_MONEY_AMOUNT,
APPLIED_MONEY_CURRENCY AS ORDERDISCOUNT_APPLIED_MONEY_CURRENCY,
AMOUNT_MONEY_AMOUNT AS ORDERDISCOUNT_AMOUNT_MONEY_AMOUNT,
AMOUNT_MONEY_CURRENCY AS ORDERDISCOUNT_AMOUNT_MONEY_CURRENCY,
__ROW_MD5 AS ORDERDISCOUNT___ROW_MD5,
__DLH_IS_DELETED AS ORDERDISCOUNT___DLH_IS_DELETED,
__DLH_SYNC_TS AS ORDERDISCOUNT___DLH_SYNC_TS,
__DLH_START_TS AS ORDERDISCOUNT___DLH_START_TS,
__DLH_FINISH_TS AS ORDERDISCOUNT___DLH_FINISH_TS,
__DLH_IS_ACTIVE AS ORDERDISCOUNT___DLH_IS_ACTIVE
FROM source
)

SELECT * FROM renamed_casted