{{ config (
  materialized= 'view',
  schema= 'SQUARE',
  tags= ["staging", "daily"]
)
}}

WITH source AS (
  SELECT * FROM  {{source('OLD_SQUARE','ORDER_LINE_ITEM')}}
),

rename AS 
(
  SELECT 
--PRIMARY KEYS  
  MD5 (UID) AS K_ORDER_LINE_DLHK,
  UID AS K_ORDER_LINE_BK,
--FOREIGN KEYS  
  ORDER_ID AS ORDERLINE_ORDER_ID,
  CATALOG_OBJECT_ID AS ORDER_LINE_CATALOG_OBJECT_ID,
  MD5( TRIM(COALESCE(CATALOG_OBJECT_ID, '00000000000000000000000000000000'))  ) AS K_CATALOG_OBJECT_DLHK,
  CATALOG_OBJECT_ID AS K_CATALOG_OBJECT_BK,
--OTHER FIELDS
  NAME AS ORDERLINE_NAME,
  QUANTITY AS ORDERLINE_QUANTITY,
  NOTE AS ORDERLINE_NOTE,
  VARIATION_NAME AS ORDERLINE_VARIATION_NAME,
  BASE_PRICE_AMOUNT AS ORDERLINE_BASE_PRICE_AMOUNT,
  BASE_PRICE_CURRENCY AS ORDERLINE_BASE_PRICE_CURRENCY,
  GROSS_SALES_AMOUNT AS ORDERLINE_GROSS_SALES_AMOUNT,
  GROSS_SALES_CURRENCY AS ORDERLINE_GROSS_SALES_CURRENCY,
  TOTAL_TAX_AMOUNT AS ORDERLINE_TOTAL_TAX_AMOUNT,
  TOTAL_TAX_CURRENCY AS ORDERLINE_TOTAL_TAX_CURRENCY,
  TOTAL_DISCOUNT_AMOUNT AS ORDERLINE_TOTAL_DISCOUNT_AMOUNT,
  TOTAL_DISCOUNT_CURRENCY AS ORDERLINE_TOTAL_DISCOUNT_CURRENCY,
  TOTAL_AMOUNT AS ORDERLINE_TOTAL_AMOUNT,
  TOTAL_CURRENCY AS ORDERLINE_TOTAL_CURRENCY
  --VARIATION_TOTAL_PRICE_AMOUNT AS ORDERLINE_VARIATION_TOTAL_PRICE_AMOUNT,
  --VARIATION_TOTAL_PRICE_CURRENCY AS ORDERLINE_VARIATION_TOTAL_PRICE_CURRENCY,
FROM source
)

SELECT * FROM rename