version: 2

sources:
  - name: OLD_SQUARE
    tables:
      - name: CUSTOMER
      - name: ORDER_DISCOUNT
      - name: ORDER_LINE_ITEM
      - name: ORDER
      - name: PAYMENT
      - name: CATALOG_ITEM
      - name: CATALOG_CATEGORY
      - name: CATALOG_ITEM_MODIFIER_LIST_INFO
      - name: CATALOG_MODIFIER_LIST
      - name: CATALOG_MODIFIER_OVERRIDE
      - name: CATALOG_MODIFIER


  