{{ config (
  materialized= 'table',
  schema= 'QUICKBOOKS',
  tags= ["staging", "daily"],
  transient=false
)
}}

SELECT 
	CAST(DATE_KEY AS NUMBER(9)) AS DATE_KEY
	,CAST(DATE_COLUMN AS DATE) AS DATE
	,CAST(FULL_DATE_DESC AS VARCHAR(64)) AS FULL_DATE_DESC
	,CAST(DAY_NUM_IN_WEEK AS NUMBER(1)) AS DAY_NUM_IN_WEEK
	,CAST(DAY_NUM_IN_MONTH AS NUMBER(2)) AS DAY_NUM_IN_MONTH
	,CAST(DAY_NUM_IN_YEAR AS NUMBER(3)) AS DAY_NUM_IN_YEAR
	,CAST(DAY_NAME AS VARCHAR(10)) AS DAY_NAME
	,CAST(DAY_ABBREV AS VARCHAR(3)) AS DAY_ABBREV
	,CAST(WEEKDAY_IND AS VARCHAR(64)) AS WEEKDAY_IND
	,CAST(US_HOLIDAY_IND AS VARCHAR(64)) AS US_HOLIDAY_IND
	,CAST(COMPANY_HOLIDAY_IND AS VARCHAR(64)) AS COMPANY_HOLIDAY_IND
	,CAST(MONTH_END_IND AS VARCHAR(64)) AS MONTH_END_IND
	,CAST(WEEK_BEGIN_DATE_NKEY AS NUMBER(9)) AS WEEK_BEGIN_DATE_NKEY
	,CAST(WEEK_BEGIN_DATE AS DATE) AS WEEK_BEGIN_DATE
	,CAST(WEEK_END_DATE_NKEY AS NUMBER(9)) AS WEEK_END_DATE_NKEY
	,CAST(WEEK_END_DATE AS DATE) AS WEEK_END_DATE
	,CAST(WEEK_NUM_IN_YEAR AS NUMBER(9)) AS WEEK_NUM_IN_YEAR
	,CAST(MONTH_NAME AS VARCHAR(10)) AS MONTH_NAME
	,CAST(MONTH_ABBREV AS VARCHAR(3)) AS MONTH_ABBREV
	,CAST(MONTH_NUM_IN_YEAR AS NUMBER(2)) AS MONTH_NUM_IN_YEAR
	,CAST(YEARMONTH AS VARCHAR(10)) AS YEARMONTH
	,CAST(CURRENT_QUARTER AS NUMBER(1)) AS QUARTER
	,CAST(YEARQUARTER AS VARCHAR(10)) AS YEARQUARTER
	,CAST(CURRENT_YEAR AS NUMBER(5)) AS "YEAR"
	,CAST(FISCAL_WEEK_NUM AS NUMBER(2)) AS FISCAL_WEEK_NUM
	,CAST(FISCAL_MONTH_NUM AS NUMBER(2)) AS FISCAL_MONTH_NUM
	,CAST(FISCAL_YEARMONTH AS VARCHAR(10)) AS FISCAL_YEARMONTH
	,CAST(FISCAL_QUARTER AS NUMBER(1)) AS FISCAL_QUARTER
	,CAST(FISCAL_YEARQUARTER AS VARCHAR(10)) AS FISCAL_YEARQUARTER
	,CAST(FISCAL_HALFYEAR AS NUMBER(1)) AS FISCAL_HALFYEAR
	,CAST(FISCAL_YEAR AS NUMBER(5)) AS FISCAL_YEAR
	,CAST(SQL_TIMESTAMP AS TIMESTAMP_NTZ) AS "SQL_TIMESTAMP"
	,CAST(CURRENT_ROW_IND AS CHAR(1)) AS CURRENT_ROW_IND
	,CAST(EFFECTIVE_DATE AS DATE) AS EFFECTIVE_DATE
	,CAST(EXPIRA_DATE AS DATE) AS EXPIRATION_DATE
FROM
{{ref('V_DATE_STG')}}